### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by alphapapa** [abingham/outline-toc.el#6]
It would be nice to have some screenshots.  :)

**Comment by abingham** [comment]
Good idea :) Fixed in 42e238bbb98536da81c60d4fed33e51f65b68a0c.

**Comment by ychaouche** [comment]
:(

emacs 24

just put `outline-toc.el` in the load path, added a `(require 'outline-toc)` in my `init.el`, then called `M-x outline-toc-mode`

![image](https://user-images.githubusercontent.com/1773693/162941348-f1d3a86b-67ca-4be3-924e-517bd829b192.png)

**Comment by abingham** [comment]
@ychaouche I'm not using or supporting this extension any more.
